services:
  app:
    image: node:22.14-alpine
    container_name: node_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
    command: |
      sh -c "
        yarn && 
        yarn prisma migrate dev && 
        yarn prisma generate && 
        if [ \"${POPULATE_DB}\" = \"YES\" ]; then 
          yarn prisma db seed; 
        fi && 
        yarn dev -p ${APP_PORT}
      "
  
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
